server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/oak01/exercises/
                    searchPaths: config-data